class BookingModel {
  static List data = [
    {
      "id_booking": 1,
      "check_in": '2024-05-10 19:18:00',
      "check_out": '2024-05-11 09:00:00',
      "duration": "01 day",
      "payment_method": "wallet",
      "total_pay": 2500000,
      "id_lodging": 1,
      "lodging_name": "S Resorts Hidden Valley Bali",
      "lodging_location":
          "Jalan Pratama Gang Welaka no 8, Tanjung Benoa, Nusa Dua, Bali, 80363 Nusa Dua, Indonesia",
      "lodging_images": [
        "assets/images/lodging6.png",
        "assets/images/lodging4.png",
      ],
      "id_user": 1,
      "username": "Dino",
      "first_name": "Dino",
      "last_name": "Wahyu",
      "email": "dinowahyu@gmail.com",
      "no_phone": "083423452211",
      "count_people_stay": 2,
      "status_booking": 1,
    },
    {
      "id_booking": 2,
      "check_in": '2024-05-13 19:18:00',
      "check_out": '2024-05-14 09:00:00',
      "duration": "01 day",
      "payment_method": "wallet",
      "total_pay": 2500000,
      "id_lodging": 1,
      "lodging_name": "S Resorts Hidden Valley Bali",
      "lodging_location":
          "Jalan Pratama Gang Welaka no 8, Tanjung Benoa, Nusa Dua, Bali, 80363 Nusa Dua, Indonesia",
      "lodging_images": [
        "assets/images/lodging6.png",
        "assets/images/lodging4.png",
      ],
      "id_user": 1,
      "username": "Dino",
      "first_name": "Dino",
      "last_name": "Wahyu",
      "email": "dinowahyu@gmail.com",
      "no_phone": "083423452211",
      "count_people_stay": 2,
      "status_booking": 0,
    },
    {
      "id_booking": 2,
      "check_in": '2024-05-16 19:18:00',
      "check_out": '2024-05-18 09:00:00',
      "duration": "02 day",
      "payment_method": "wallet",
      "total_pay": 2500000,
      "id_lodging": 1,
      "lodging_name": "S Resorts Hidden Valley Bali",
      "lodging_location":
          "Jalan Pratama Gang Welaka no 8, Tanjung Benoa, Nusa Dua, Bali, 80363 Nusa Dua, Indonesia",
      "lodging_images": [
        "assets/images/lodging6.png",
        "assets/images/lodging4.png",
      ],
      "id_user": 1,
      "username": "Dino",
      "first_name": "Dino",
      "last_name": "Wahyu",
      "email": "dinowahyu@gmail.com",
      "no_phone": "083423452211",
      "count_people_stay": 2,
      "status_booking": 1,
    },
  ];
}
